version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tickets-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tickets
      POSTGRES_USER: tickets_user
      POSTGRES_PASSWORD: tickets_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
